name: flutter_facebook_instagram_login
description: Login via Facebook. Easily add Facebook login feature in your application. User profile information included.
version: 2.0.1
homepage: https://www.thanhdt.dev/
repository: https://github.com/thanhdang198/flutter_login_facebook
issue_tracker: https://github.com/thanhdang198/flutter_login_facebook/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  list_ext: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  innim_lint: ^0.3.1

flutter:
  plugin:
    platforms:
      android:
        package: ru.innim.flutter_login_facebook
        pluginClass: FlutterLoginFacebookPlugin
      ios:
        pluginClass: FlutterLoginFacebookPlugin
